import { spawn } from "child_process";
import fs from "fs";
import os from "os";
import path from "path";
import { downloadTimeoutMs } from "./duration-limits";
import { getYtdlpCookiesPath } from "./ytdlp-cookies";
import { pickEnglishDownloadLang, subtitleLangs } from "./subtitle-languages";
import { srtFileToYoutubeTranscriptText } from "./youtube-transcript";

export type VideoQuality = "360p" | "480p" | "720p" | "1080p";

const FORMAT: Record<VideoQuality, string> = {
  "360p": "bestvideo[height<=360][ext=mp4]+bestaudio[ext=m4a]/best[height<=360]",
  "480p": "bestvideo[height<=480][ext=mp4]+bestaudio[ext=m4a]/best[height<=480]",
  "720p": "bestvideo[height<=720][ext=mp4]+bestaudio[ext=m4a]/best[height<=720]",
  "1080p": "bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[height<=1080]",
};

const PLAYER_CLIENTS = [
  "android_vr,tv,ios,android",
  "mweb,web_safari,web",
  "web_embedded",
];

export interface DownloadResult {
  filePath: string;
  fileName: string;
  fileSizeBytes: number;
  fileSizeMB: number;
  transcriptPath: string | null;
  transcriptLang: string | null;
  transcriptAutoGenerated: boolean;
}

function isBotBlockError(message: string): boolean {
  return /not a bot|Sign in to confirm|bot check|HTTP Error 403|rate-limited|This content isn't available, try again later/i.test(
    message
  );
}

function pickSubtitleFile(stemPath: string): { filePath: string; lang: string } | null {
  const dir = path.dirname(stemPath);
  const stem = path.basename(stemPath);
  const escaped = stem.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const pattern = new RegExp(`^${escaped}\\.([^.]+)\\.srt$`, "i");

  const candidates = fs
    .readdirSync(dir)
    .map((name) => {
      const match = name.match(pattern);
      if (!match) return null;
      return { filePath: path.join(dir, name), lang: match[1] };
    })
    .filter((entry): entry is { filePath: string; lang: string } => entry !== null);

  if (!candidates.length) return null;

  const preferred = pickEnglishDownloadLang(candidates.map((c) => c.lang));
  if (!preferred) return null;

  return candidates.find((c) => c.lang.toLowerCase() === preferred.toLowerCase()) ?? null;
}

function writeYoutubeTranscriptFile(srtPath: string, lang: string, stemPath: string): string | null {
  const header =
    lang.toLowerCase() === "en-orig" || lang.toLowerCase().startsWith("en")
      ? "English (auto-generated)"
      : undefined;
  const text = srtFileToYoutubeTranscriptText(srtPath, { header });
  if (!text.trim()) return null;

  const safeLang = lang.replace(/[^a-zA-Z0-9-]/g, "").slice(0, 16) || "en";
  const outPath = `${stemPath}.${safeLang}.youtube.txt`;
  fs.writeFileSync(outPath, text, "utf8");
  return outPath;
}

function isAutoGeneratedLang(lang: string): boolean {
  const lower = lang.toLowerCase();
  return lower === "en-orig" || lower.startsWith("en");
}

function pickSubtitleFromStem(stemPath: string): { filePath: string; lang: string } | null {
  const picked = pickSubtitleFile(stemPath);
  if (!picked) return null;
  const youtubePath = writeYoutubeTranscriptFile(picked.filePath, picked.lang, stemPath);
  if (!youtubePath) return null;
  return { filePath: youtubePath, lang: picked.lang };
}

function ytdlpBaseArgs(
  quality: VideoQuality | null,
  playerClients: string,
  stemPath: string,
  skipVideo: boolean
): string[] {
  const template = `${stemPath}.%(ext)s`;
  const args: string[] = [];

  if (skipVideo) {
    args.push("--skip-download");
  } else {
    args.push("--format", FORMAT[quality!], "--merge-output-format", "mp4");
  }

  args.push(
    "--write-subs",
    "--write-auto-subs",
    "--sub-langs",
    subtitleLangs(),
    "--convert-subs",
    "srt",
    "--extractor-args",
    `youtube:player_client=${playerClients}`,
    "--output",
    template,
    "--no-playlist",
    "--no-warnings",
    "--quiet",
    "--user-agent",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
  );

  if (!skipVideo) {
    args.push(
      "--no-part",
      "--retries",
      "3",
      "--fragment-retries",
      "3",
      "--concurrent-fragments",
      "4"
    );
  }

  const cookiesPath = getYtdlpCookiesPath();
  if (cookiesPath) args.push("--cookies", cookiesPath);

  return args;
}

function runYtdlp(
  url: string,
  videoId: string,
  quality: VideoQuality | null,
  playerClients: string,
  stemPath: string,
  effectiveTimeout: number,
  skipVideo: boolean
): Promise<void> {
  const args = [...ytdlpBaseArgs(quality, playerClients, stemPath, skipVideo), url];

  return new Promise((resolve, reject) => {
    const proc = spawn("yt-dlp", args, {
      env: { ...process.env, PATH: process.env.PATH || "/usr/local/bin:/usr/bin:/bin" },
    });
    let stderr = "";
    proc.stderr?.on("data", (d) => {
      stderr += d.toString();
    });
    const timer = setTimeout(() => {
      proc.kill("SIGTERM");
      reject(new Error(`yt-dlp timeout for ${videoId}`));
    }, effectiveTimeout);
    proc.on("close", (code) => {
      clearTimeout(timer);
      if (code !== 0) {
        reject(new Error(`yt-dlp exit ${code}: ${stderr.slice(0, 400)}`));
        return;
      }
      resolve();
    });
    proc.on("error", (err) => {
      clearTimeout(timer);
      reject(err);
    });
  });
}

function resolveDownloadOutput(stemPath: string): DownloadResult {
  const mp4 = `${stemPath}.mp4`;
  const mkv = `${stemPath}.mkv`;
  const p = fs.existsSync(mp4) ? mp4 : fs.existsSync(mkv) ? mkv : null;
  if (!p) throw new Error(`Output not found`);
  const stats = fs.statSync(p);
  const subtitle = pickSubtitleFromStem(stemPath);

  return {
    filePath: p,
    fileName: path.basename(p),
    fileSizeBytes: stats.size,
    fileSizeMB: Math.round((stats.size / 1024 / 1024) * 10) / 10,
    transcriptPath: subtitle?.filePath ?? null,
    transcriptLang: subtitle?.lang ?? null,
    transcriptAutoGenerated: subtitle ? isAutoGeneratedLang(subtitle.lang) : false,
  };
}

function runYtdlpOnce(
  url: string,
  videoId: string,
  quality: VideoQuality,
  playerClients: string,
  stemPath: string,
  effectiveTimeout: number
): Promise<DownloadResult> {
  return runYtdlp(url, videoId, quality, playerClients, stemPath, effectiveTimeout, false).then(
    () => resolveDownloadOutput(stemPath)
  );
}

async function fetchSubsOnly(
  url: string,
  videoId: string,
  stemPath: string,
  effectiveTimeout: number
): Promise<{ filePath: string; lang: string } | null> {
  for (const clients of PLAYER_CLIENTS) {
    try {
      await runYtdlp(url, videoId, null, clients, stemPath, Math.min(effectiveTimeout, 120_000), true);
      const subtitle = pickSubtitleFromStem(stemPath);
      if (subtitle) return subtitle;
    } catch {
      // try next client
    }
  }
  return null;
}

export async function downloadYouTubeVideo(
  url: string,
  videoId: string,
  quality: VideoQuality = "720p",
  durationSeconds = 0,
  timeoutMs?: number
): Promise<DownloadResult> {
  const stamp = Date.now();
  const stemPath = path.join(os.tmpdir(), `yt_${videoId}_${stamp}`);
  const effectiveTimeout = timeoutMs ?? downloadTimeoutMs(durationSeconds);
  let lastError = "yt-dlp failed";

  for (const clients of PLAYER_CLIENTS) {
    try {
      const result = await runYtdlpOnce(url, videoId, quality, clients, stemPath, effectiveTimeout);
      if (!result.transcriptPath) {
        const subs = await fetchSubsOnly(url, videoId, stemPath, effectiveTimeout);
        if (subs) {
          return {
            ...result,
            transcriptPath: subs.filePath,
            transcriptLang: subs.lang,
            transcriptAutoGenerated: isAutoGeneratedLang(subs.lang),
          };
        }
      }
      return result;
    } catch (err: unknown) {
      lastError = err instanceof Error ? err.message : String(err);
      if (!isBotBlockError(lastError)) {
        throw err instanceof Error ? err : new Error(lastError);
      }
    }
  }

  throw new Error(lastError);
}

export function cleanupTempFile(p: string) {
  try {
    if (fs.existsSync(p)) fs.unlinkSync(p);
  } catch {
    /* ignore cleanup errors */
  }
}

export function cleanupTempSubtitleStem(stemPath: string) {
  const dir = path.dirname(stemPath);
  const stem = path.basename(stemPath);
  try {
    for (const name of fs.readdirSync(dir)) {
      if (!name.startsWith(stem)) continue;
      if (name.endsWith(".srt") || name.endsWith(".youtube.txt")) {
        cleanupTempFile(path.join(dir, name));
      }
    }
  } catch {
    /* ignore cleanup errors */
  }
}
